# AutoInform Configuration

# This section defines multiple protected zones.
# Each zone can be configured to either alert staff or deny placement
# of banned materials within its boundaries.
zones:
  # Example Zone 1: Alerts staff only (default behavior)
  zone_alpha: # Unique name for this zone
    world: "world"
    corner1:
      x: 0.0
      y: 64.0
      z: 0.0
    corner2:
      x: 100.0
      y: 100.0
      z: 100.0
    # Set to true to prevent placement of banned materials in this zone.
    # Set to false (or omit) to only alert staff.
    deny-placement: false

  # Example Zone 2: Denies placement
  zone_beta: # Another unique name for a different zone
    world: "world_nether"
    corner1:
      x: -50.0
      y: 30.0
      z: -50.0
    corner2:
      x: 50.0
      y: 80.0
      z: 50.0
    deny-placement: true # This zone will deny placement of banned materials

# This section defines a list of materials that are generally considered "banned".
# Zones will only apply actions to materials present in this global list,
# unless a specific 'ALLOW' action is defined within a zone's material-actions.
banned-materials:
  - LAVA_BUCKET
  - TNT
  - TNT_MINECART

# --- NEW: Custom Region Definitions ---
# This section defines custom regions with specific restrictions for block placement,
# chest interactions, and item usage.
# Regions are defined by two corner vectors and can have lists of banned materials
# or a boolean for chest interaction.
regions:
# Example Region:
# my_spawn_region:
#   name: my_spawn_region
#   world: world
#   min: {x: 0.0, y: 60.0, z: 0.0}
#   max: {x: 100.0, y: 100.0, z: 100.0}
#   banned_block_placement:
#     - STONE
#     - TNT
#   ban_chest_interaction: true
#   banned_item_usage:
#     - GOLDEN_APPLE
#     - ENDER_PEARL