# AutoInform Configuration
#
# This section defines multiple protected zones.
# Each zone can be configured with specific actions (DENY, ALERT, ALLOW)
# for different materials, and a default action for others.

zones:
  # Example Zone 1: Default action is ALERT, but LAVA_BUCKET is DENIED
  zone_alpha:
    world: "world"
    corner1:
      x: 0.0
      y: 64.0
      z: 0.0
    corner2:
      x: 100.0
      y: 100.0
      z: 100.0
    # Default action for materials in this zone if not specified in material-actions.
    # Options: DENY, ALERT, ALLOW
    default-material-action: ALERT

    # Specific actions for materials within this zone.
    # These override the default-material-action for the listed materials.
    material-actions:
      LAVA_BUCKET: DENY   # Deny placement of lava in this zone
      TNT: ALERT          # Only alert staff for TNT placement
      WATER_BUCKET: ALLOW # Allow water placement, even if it's in the global banned-materials list

  # Example Zone 2: Default action is DENY
  zone_beta:
    world: "world_nether"
    corner1:
      x: -50.0
      y: 30.0
      z: -50.0
    corner2:
      x: 50.0
      y: 100.0
      z: 50.0
    default-material-action: DENY
    material-actions:
      OBSIDIAN: ALLOW # Allow obsidian placement in this zone

# Global Banned Materials
# Materials listed here will be DENIED if a player attempts to place them
# OUTSIDE of any defined AutoInform zone.
#
# Zone-specific 'material-actions' (DENY, ALERT, ALLOW) in the 'zones' section
# will always OVERRIDE this global list for actions taken within that zone.
#
# Example: If WATER_BUCKET is in 'banned-materials' globally, but 'zone_alpha'
# has WATER_BUCKET: ALLOW, then water can be placed in 'zone_alpha'.
banned-materials:
  - LAVA_BUCKET
  - TNT
  - SPAWNER
  - BEDROCK
  - COMMAND_BLOCK
  - BARRIER