# AutoInform Configuration

# This section defines multiple protected zones.
# Each zone can be configured with specific actions (DENY, ALERT, ALLOW)
# for different materials, and a default action for others.
zones:
  # Example Zone 1: Default action is ALERT, but LAVA_BUCKET is DENIED
  zone_alpha:
    world: "world"
    corner1:
      x: 0.0
      y: 64.0
      z: 0.0
    corner2:
      x: 100.0
      y: 100.0
      z: 100.0
    # Default action for materials in this zone if not specified in material-actions.
    # Options: DENY, ALERT, ALLOW
    default-material-action: ALERT

    # Specific actions for materials within this zone.
    # These override the default-material-action for the listed materials.
    material-actions:
      LAVA_BUCKET: DENY   # Deny placement of lava in this zone
      TNT: ALERT          # Only alert staff for TNT placement
      WATER_BUCKET: ALLOW # Allow water placement, even if it's in the global banned-materials list

  # Example Zone 2: Default action is DENY
  zone_beta:
    world: "world_nether"
    corner1:
      x: -50.0
      y: 30.0
      z: -50.0
    corner2:
      x: 50.0
      y: 80.0
      z: 50.0
    default-material-action: DENY # Deny all banned materials by default in this zone
    material-actions:
      FIRE: ALERT # But only alert for fire, don't deny

# This section defines a list of materials that are generally considered "banned".
# Zones will only apply actions to materials present in this global list,
# unless a specific 'ALLOW' action is defined within a zone's material-actions.
banned-materials:
  - LAVA_BUCKET
  - TNT
  - TNT_MINECART
  - FIRE
  - WATER_BUCKET # Example: Water is generally banned, but zone_alpha allows it.

# --- Global Settings ---
# Set to true to enable logging and staff alerts for chest access within any defined AutoInform zone.
# Requires CoreProtect to be installed and enabled.
monitor-chest-access: true # Default value

# Customizable messages for the plugin.
# These messages support Minecraft color codes (e.g., &a for green).
# The {plugin-prefix} placeholder will be automatically replaced by the value at the top of this file.
messages:
  plugin-prefix: "&c[AutoInform] &e" # This is the actual prefix definition
  plugin-startup: "{plugin-prefix}Plugin starting..."
  plugin-enabled: "{plugin-prefix}Plugin enabled!"
  plugin-shutting-down: "{plugin-prefix}Plugin shutting down..."
  plugin-disabled: "{plugin-prefix}Plugin disabled!"
  plugin-config-reloaded: "{plugin-prefix}Configuration reloaded."
  plugin-warning-no-zones-old: "{plugin-prefix}No old AutoInform zones are defined. Use &f/{command} define <name>&e to create one."
  plugin-success-zones-loaded-old: "{plugin-prefix}Loaded {count} old AutoInform zones."
  plugin-warning-no-regions: "{plugin-prefix}No regions are defined. Use &f/autowarn region select <name>&e to create one."
  plugin-success-regions-loaded: "{plugin-prefix}Loaded {count} regions."
  plugin-current-banned-materials: "{plugin-prefix}Globally banned materials: &f{materials}"
  plugin-no-zones-in-config: "{plugin-prefix}No 'zones' section found in config.yml. No old AutoInform zones loaded."
  plugin-invalid-zone-config: "{plugin-prefix}Invalid configuration for zone '{zone_name}'. Skipping."
  plugin-world-not-found: "{plugin-prefix}World '{world_name}' for zone '{zone_name}' not found! This zone will not be active."
  plugin-error-loading-zone-coords: "{plugin-prefix}Error loading coordinates for zone '{zone_name}': {message}"
  plugin-invalid-banned-material-config: "{plugin-prefix}Invalid material '{name}' in banned-materials list. Skipping."
  plugin-invalid-material-zone-config: "{plugin-prefix}Invalid material or action type in zone '{zone_name}' for material '{material_name}'. Skipping: {message}"
  plugin-loaded-zone: "{plugin-prefix}Loaded zone '{zone_name}' in world '{world_name}' (Default Action: {default_action})."
  plugin-coreprotect-not-found: "{plugin-prefix}CoreProtect plugin not found. CoreProtect integration is disabled."
  plugin-coreprotect-hooked: "{plugin-prefix}CoreProtect API hooked successfully."
  plugin-coreprotect-api-disabled: "{plugin-prefix}CoreProtect API is disabled. Some features might not work."
  plugin-coreprotect-api-outdated: "{plugin-prefix}CoreProtect API version is {version}. Please update CoreProtect for full compatibility."
  plugin-coreprotect-lookup-failed: "{plugin-prefix}CoreProtect lookup failed for {location}: {message}"
  plugin-monitor-chest-access-enabled: "{plugin-prefix}Chest access monitoring is enabled."
  plugin-monitor-chest-access-disabled: "{plugin-prefix}Chest access monitoring is disabled."
  plugin-toggle-chest-monitor-success: "{plugin-prefix}Chest access monitoring set to: &f{status}"
  plugin-toggle-chest-monitor-requires-coreprotect: "{plugin-prefix}Cannot toggle chest monitoring: CoreProtect is not loaded or enabled."
  player-no-permission: "{plugin-prefix}You do not have permission to use this command."
  player-command-usage: "{plugin-prefix}Usage: {usage}"
  player-console-only-reload: "{plugin-prefix}Only console can use '{command_name} reload'. Players use '/{command_name} reload'."
  player-wand-received: "{plugin-prefix}You have received the AutoInform Zone Selector Wand!"
  player-wand-pos1-set: "{plugin-prefix}Position 1 set to {location}."
  player-wand-pos2-set: "{plugin-prefix}Position 2 set to {location}."
  player-wand-click-block: "{plugin-prefix}You must click on a block to set Position {pos_num}."
  player-wand-selections-cleared: "{plugin-prefix}Your wand selections have been cleared."
  player-positions-same-world: "{plugin-prefix}Both positions must be in the same world."
  player-define-zone-success: "{plugin-prefix}AutoInform zone '{zone_name}' defined and saved for world '{world_name}'."
  player-define-zone-corners: "{plugin-prefix}Corner 1: {corner1_loc}\n{plugin-prefix}Corner 2: {corner2_loc}"
  player-define-zone-default-action-setting: "{plugin-prefix}Default Action: {default_action}"
  player-define-zone-manual-selection: "{plugin-prefix}Using manual selections for zone '{zone_name}'."
  player-define-zone-wand-selection: "{plugin-prefix}Using wand selections for zone '{zone_name}'."
  player-zone-removed: "{plugin-prefix}Zone '{zone_name}' has been removed."
  player-zone-not-found: "{plugin-prefix}Zone '{zone_name}' not found."
  player-no-zones-defined: "{plugin-prefix}No AutoInform zones are currently defined."
  player-all-zones-header: "--- {plugin-prefix}All AutoInform Zones ---"
  player-defined-zones-header: "--- {plugin-prefix}Defined AutoInform Zones ---"
  player-zone-info-header: "--- {plugin-prefix}AutoInform Zone: {zone_name} ---"
  player-zone-info-world: "{plugin-prefix}World: &f{world_name}"
  player-zone-info-corner1: "{plugin-prefix}Corner 1: &f{corner1_loc}"
  player-zone-info-corner2: "{plugin-prefix}Corner 2: &f{corner2_loc}"
  player-zone-info-default-action: "{plugin-prefix}Default Action: &f{default_action}"
  player-zone-info-material-actions: "{plugin-prefix}Material Actions:"
  player-zone-info-material-action-entry: "{plugin-prefix}  - {material}: {action}"
  player-zone-list-entry: "{plugin-prefix}- {zone_name}: &fWorld: {world_name}, Default: {default_action}"
  player-default-action-updated: "{plugin-prefix}Default action for zone '{zone_name}' set to {action}."
  player-material-action-updated: "{plugin-prefix}Action for {material} in zone '{zone_name}' set to {action}."
  player-invalid-action-type: "{plugin-prefix}Invalid action type. Please use DENY, ALERT, or ALLOW."
  player-invalid-boolean-value: "{plugin-prefix}Invalid value. Please use 'true' or 'false'."
  player-material-added-banned: "{plugin-prefix}Material '{material}' added to banned list."
  player-material-already-banned: "{plugin-prefix}Material '{material}' is already in the banned list."
  player-material-removed-banned: "{plugin-prefix}Material '{material}' removed from banned list."
  player-material-not-banned: "{plugin-prefix}Material '{material}' is not in the banned list."
  player-invalid-material-name: "{plugin-prefix}Invalid material name: '{material}'. Please use a valid Minecraft material name (e.g., LAVA_BUCKET, TNT)."
  player-no-materials-banned: "{plugin-prefix}No materials are currently banned."
  player-banned-materials-header: "--- {plugin-prefix}Banned Materials ---"
  player-banned-unknown-subcommand: "{plugin-prefix}Unknown 'banned' subcommand. Usage: &f/{command_name} banned <add|remove|list>"
  staff-alert-message: "{action_color}[AutoInform Alert] &ePlayer &b{player} &eattempted &c{action_status} &eaction with &b{material} &eat &fX:{x} Y:{y} Z:{z} &ein zone &a'{zone_name}'."
  staff-alert-chest-access: "{action_color}[AutoInform Alert] &ePlayer &b{player} &eaccessed chest at &fX:{x} Y:{y} Z:{z} &ein zone &a'{zone_name}'."
  main-help-header: "--- {plugin-prefix}AutoInform Setter Help ---"
  main-help-wand: "{plugin-prefix}/{command} wand &f- Get the selection wand."
  main-help-pos1: "{plugin-prefix}/{command} <zone_name> pos1 &f- Set first zone corner (manual)."
  main-help-pos2: "{plugin-prefix}/{command} <zone_name> pos2 &f- Set second zone corner (manual)."
  main-help-define: "{plugin-prefix}/{command} <zone_name> define &f- Define/update <zone_name> using wand or manual selections."
  main-help-defaultaction: "{plugin-prefix}/{command} <zone_name> defaultaction <DENY|ALERT|ALLOW> &f- Set default action for a zone."
  main-help-setaction: "{plugin-prefix}/{command} <zone_name> setaction <material> <DENY|ALERT|ALLOW> &f- Set specific material action for a zone."
  main-help-remove: "{plugin-prefix}/{command} remove <zone_name> &f- Remove a defined zone."
  main-help-info: "{plugin-prefix}/{command} info [zone_name] &f- Show info for a specific zone or all zones."
  main-help-list: "{plugin-prefix}/{command} list &f- List all defined zones."
  main-help-clearwand: "{plugin-prefix}/{command} clearwand &f- Clear your wand selections."
  main-help-reload: "{plugin-prefix}/{command} reload &f- Reload all zones and banned materials from config."
  main-help-banned: "{plugin-prefix}/{command} banned <add|remove|list> &f- Manage banned materials."
  main-help-togglechestmonitor: "{plugin-prefix}/{command} togglechestmonitor &f- Toggle global chest access monitoring."
  main-help-note: "{plugin-prefix}Note: Actions are configurable per-zone and per-material."