main: net.Alexxiconify.alexxAutoWarn.AlexxAutoWarn
version: 1.0.0 # Make sure this matches your plugin version
api-version: 1.20 # Adjust this to your Minecraft server's API version (e.g., 1.19, 1.20, 1.21)
name: AlexxAutoWarn
commands:
  autoinform:
    description: Manages AutoInform zones and settings.
    usage: /<command> <subcommand>
    aliases: [ ainform ]
    permission: autoinform.admin.set # All main commands require this permission
    permission-message: You do not have permission to use this command.
permissions:
  autoinform.admin.set:
    description: Allows setting and managing AutoInform zones and plugin settings.
    default: staff # staff get this permission by default
  autoinform.alert.receive:
    description: Allows a player to receive in-game alerts when a monitored action occurs.
    default: staff # staff receive alerts by default
  autoinform.bypass:
    description: Allows a player to bypass all AutoInform zone restrictions (no denials or alerts).
    default: staff # This permission should be granted explicitly to bypassers