#file: noinspection SpellCheckingInspection
name: AlexxAutoWarn
version: '1.0.0-SNAPSHOT'
main: net.Alexxiconify.alexxAutoWarn.AlexxsAutoWarn.AlexxAutoWarn
api-version: '1.21'
commands:
  ainformset:
    description: Manages AutoInform zones and banned materials.
    usage: /ainformset <subcommand>
    aliases: [ autoinform, aw ] # Added aliases for convenience
    permission: autoinform.admin.set
permissions:
  autoinform.admin.set:
    description: Allows access to AutoInform zone and banned material setting commands.
    default: op
  autoinform.alert.receive: # Existing permission for staff alerts
    description: Allows players to receive alerts about banned material placement.
    default: op
  alexxautowarn.region.admin: # New permission for region management commands
    description: Allows access to custom region management commands (create, delete, modify regions).
    default: op
  alexxautowarn.region.bypass: # New permission for bypassing region restrictions
    description: Allows bypassing all custom region restrictions (block placement, chest interaction, item usage).
    default: op