# AutoInform Configuration

# This section defines multiple protected zones.
# Each zone can be configured with specific actions (DENY, ALERT, ALLOW)
# for different materials, and a default action for others.
zones:
  # Example Zone 1: Default action is ALERT, but LAVA_BUCKET is DENIED
  zone_alpha:
    world: "world"
    corner1:
      x: 0.0
      y: 64.0
      z: 0.0
    corner2:
      x: 100.0
      y: 100.0
      z: 100.0
    # Default action for materials in this zone if not specified in material-actions.
    # Options: DENY, ALERT, ALLOW
    default-material-action: ALERT

    # Specific actions for materials within this zone.
    # These override the default-material-action for the listed materials.
    material-actions:
      LAVA_BUCKET: DENY   # Deny placement of lava in this zone
      TNT: ALERT          # Only alert staff for TNT placement
      WATER_BUCKET: ALLOW # Allow water placement, even if it's in the global banned-materials list

  # Example Zone 2: Default action is DENY
  zone_beta:
    world: "world_nether"
    corner1:
      x: -50.0
      y: 30.0
      z: -50.0
    corner2:
      x: 50.0
      y: 80.0
      z: 50.0
    default-material-action: DENY # Deny all banned materials by default in this zone
    material-actions:
      FIRE: ALERT # But only alert for fire, don't deny

# This section defines a list of materials that are generally considered "banned".
# Zones will only apply actions to materials present in this global list,
# unless a specific 'ALLOW' action is defined within a zone's material-actions.
banned-materials:
  - LAVA_BUCKET
  - TNT
  - TNT_MINECART
  - FIRE
  - WATER_BUCKET # Example: Water is generally banned, but zone_alpha allows it.

# Customizable messages for the plugin.
messages:
  player-denied-placement: "&cYou are not allowed to place {material} here!"
  player-wand-pos1-set: "&aPosition 1 set: {location}"
  player-wand-pos2-set: "&aPosition 2 set: {location}"
  player-wand-click-block: "&eYou must click on a block to set Position {pos_num}."
  player-wand-received: "&aYou have received the AutoInform Zone Selector Wand!"
  player-positions-same-world: "&cBoth positions must be in the same world."
  player-define-zone-success: "&aAutoInform zone '{zone_name}' defined and saved for world '{world_name}'."
  player-define-zone-corners: "&7Corner 1: {corner1_loc}\n&7Corner 2: {corner2_loc}"
  player-define-zone-deny-setting: "&7Default Action: {default_action}"
  player-zone-removed: "&aZone '{zone_name}' has been removed."
  player-zone-not-found: "&eZone '{zone_name}' not found."
  player-no-zones-defined: "&eNo AutoInform zones are currently defined."
  player-all-zones-header: "&b--- All AutoInform Zones ---"
  player-zone-info-header: "&b--- AutoInform Zone: {zone_name} ---"
  player-zone-info-world: "&6World: &f{world_name}"
  player-zone-info-corner1: "&6Corner 1: &f{corner1_loc}"
  player-zone-info-corner2: "&6Corner 2: &f{corner2_loc}"
  player-zone-info-default-action: "&6Default Action: &f{default_action}"
  player-zone-info-material-actions: "&6Material Actions:"
  player-zone-info-material-action-entry: "&f  - {material}: {action}"
  player-defined-zones-header: "&b--- Defined AutoInform Zones ---"
  player-wand-selections-cleared: "&aYour wand selections have been cleared."
  player-material-added-banned: "&aMaterial '{material}' added to banned list."
  player-material-already-banned: "&eMaterial '{material}' is already in the banned list."
  player-invalid-material-name: "&cInvalid material name: '{material}'. Please use a valid Minecraft material name (e.g., LAVA_BUCKET, TNT)."
  player-material-removed-banned: "&aMaterial '{material}' removed from banned list."
  player-material-not-banned: "&eMaterial '{material}' is not in the banned list."
  player-no-materials-banned: "&eNo materials are currently banned."
  player-banned-materials-header: "&b--- Banned Materials ---"
  player-deny-setting-updated: "&aDefault action for zone '{zone_name}' set to {action}."
  player-material-action-updated: "&aAction for {material} in zone '{zone_name}' set to {action}."
  player-invalid-action-type: "&cInvalid action type. Please use DENY, ALERT, or ALLOW."
  player-no-permission: "&cYou do not have permission to use this command."
  player-command-usage: "&cUsage: {usage}"
  player-console-only-reload: "&cThis command can only be run by a player (except for /{command_name} reload)."
  staff-alert-message: "&c[AutoInform] &e{player} placed {material} in zone '{zone_name}' at {x},{y},{z}. Action: {action_color}{action_status}."
  plugin-config-reloaded: "&aAutoInform configuration reloaded."
  plugin-warning-no-zones: "&eWarning: No zones defined in config or some worlds are invalid."
  plugin-success-zones-loaded: "&bSuccessfully loaded {count} zone(s)."
  plugin-current-banned-materials: "&bCurrently banned materials: {materials}"
  plugin-enabled: "AutoInform enabled!"
  plugin-disabled: "AutoInform disabled!"
  plugin-coreprotect-not-found: "CoreProtect API not found! Related functionality might be affected."
  plugin-coreprotect-hooked: "CoreProtect API hooked successfully."
  plugin-coreprotect-api-disabled: "CoreProtect API is not enabled."
  plugin-coreprotect-api-outdated: "CoreProtect API version is outdated (found: {version}). Please update CoreProtect."
  plugin-invalid-zone-config: "Invalid configuration for zone '{zone_name}'. Skipping."
  plugin-world-not-found: "World '{world_name}' for zone '{zone_name}' not found! This zone will not be active."
  plugin-error-loading-zone-coords: "Error loading coordinates for zone '{zone_name}': {message}. Skipping."
  plugin-invalid-banned-material-config: "Invalid material name '{name}' found in config.yml banned-materials list. Skipping."
  plugin-no-zones-in-config: "No 'zones' section found in config.yml. No zones loaded."
