# AutoInform Configuration

# This section defines multiple protected zones.
# Each zone can be configured with specific actions (DENY, ALERT, ALLOW)
# for different materials, and a default action for others.
zones:
  # Example Zone 1: Default action is ALERT, but LAVA_BUCKET is DENIED
  zone_alpha:
    world: "world"
    # Corrected corner1 and corner2 to a single string format: "x,y,z"
    corner1: "0.0,64.0,0.0"
    corner2: "100.0,100.0,100.0"
    # Default action for materials in this zone if not specified in material-actions.
    # Options: DENY, ALERT, ALLOW
    default-material-action: ALERT

    # Specific actions for materials within this zone.
    # These override the default-material-action for the listed materials.
    material-actions:
      LAVA_BUCKET: DENY   # Deny placement of lava in this zone
      TNT: ALERT          # Only alert staff for TNT placement
      WATER_BUCKET: ALLOW # Allow water placement, even if it's in the global banned-materials list

  # Example Zone 2: Default action is DENY
  zone_beta:
    world: "world_nether"
    # Corrected corner1 and corner2 to a single string format: "x,y,z"
    corner1: "-50.0,30.0,-50.0"
    corner2: "50.0,100.0,50.0"
    default-material-action: DENY
    material-actions:
      OBSIDIAN: ALLOW # Allow obsidian in nether zones, even if general deny

# Global list of materials that are banned everywhere unless explicitly ALLOWED in a zone.
globally-banned-materials:
  - BEDROCK
  - COMMAND_BLOCK
  - BARRIER
  - LIGHT
  - STRUCTURE_BLOCK
  - JIGSAW
  - DIRT

# Global setting: whether to monitor chest access (opening/closing of container blocks like chests, barrels, etc.)
# If set to true, PlayerInteractEvent will check if container opening triggers an alert.
# Note: CoreProtect integration for chest access logging might need specific CoreProtect API calls.
monitor-chest-access: false

# Debug setting for logging allowed actions (useful for troubleshooting)
debug-log-allowed-actions: false

# Customizable messages for the AlexxAutoWarn plugin.
# All messages support color codes using '&'.
# Placeholders are replaced dynamically, e.g., {player}, {zone_name}.
messages:
  # General Plugin Prefix - applied to almost all messages for consistent branding
  plugin-prefix: "&c[AutoInform] &e"

  # --- General Plugin & CoreProtect Messages ---
  plugin-startup: "{plugin-prefix}Plugin starting..."
  plugin-enabled: "{plugin-prefix}Plugin enabled!"
  plugin-shutting-down: "{plugin-prefix}Plugin shutting down..."
  plugin-disabled: "{plugin-prefix}Plugin disabled!"
  plugin-config-reloaded: "{plugin-prefix}Configuration reloaded."
  plugin-warning-no-zones-old: "{plugin-prefix}No old AutoInform zones are defined. Use &f/{command} define <name>&e to create one."
  plugin-success-zones-loaded-old: "{plugin-prefix}Loaded {count} old AutoInform zones."
  plugin-warning-no-regions: "{plugin-prefix}No regions are defined. Use &f/autowarn region select <name>&e to create one."
  plugin-success-regions-loaded: "{plugin-prefix}Loaded {count} regions."
  plugin-current-banned-materials: "{plugin-prefix}Globally banned materials: &f{materials}"
  plugin-no-zones-in-config: "{plugin-prefix}No 'zones' section found in config.yml. No zones loaded."
  plugin-invalid-zone-config: "{plugin-prefix}&cInvalid configuration for zone '{zone_name}'. Skipping."
  plugin-world-not-found: "{plugin-prefix}&cWorld '{world_name}' for zone '{zone_name}' not found! This zone will not be active."
  plugin-error-loading-zone: "{plugin-prefix}&cError loading zone '{zone_name}': {error}"
  plugin-zones-loaded: "{plugin-prefix}Loaded {count} zones."
  plugin-zones-saved: "{plugin-prefix}Saved {count} zones to config."
  plugin-banned-materials-loaded: "{plugin-prefix}Loaded {count} globally banned materials."
  plugin-banned-materials-saved: "{plugin-prefix}Saved {count} globally banned materials to config."
  plugin-invalid-banned-material: "{plugin-prefix}&cInvalid material '{material_name}' in globally-banned-materials list. Skipping."
  plugin-invalid-material-action-config: "{plugin-prefix}&cInvalid material or action '{material_or_action}' for zone '{zone_name}'. Skipping."
  plugin-coreprotect-not-found: "{plugin-prefix}&cCoreProtect not found! Logging to console only."
  plugin-coreprotect-found: "{plugin-prefix}CoreProtect found and hooked!"
  plugin-monitor-chest-access-enabled: "{plugin-prefix}Chest access monitoring is enabled."
  plugin-monitor-chest-access-disabled: "{plugin-prefix}Chest access monitoring is disabled."
  plugin-toggle-chest-monitor-success: "{plugin-prefix}Chest access monitoring set to &f{status}&e."

  # --- New/Corrected ZoneManager specific messages ---
  zone-config-missing-world: "{plugin-prefix}&cZone '{zone_name}' is missing a 'world' setting in config.yml. Skipping."
  zone-config-missing-corners: "{plugin-prefix}&cZone '{zone_name}' is missing 'corner1' or 'corner2' settings in config.yml. Skipping."
  zone-config-invalid-material-action: "{plugin-prefix}&cInvalid material action in zone '{zone_name}' for material '{material_key}': {error}. Skipping."
  plugin-invalid-zone-config-error: "{plugin-prefix}&cError parsing zone '{zone_name}' from config: {error}. Skipping."
  zone-loaded: "{plugin-prefix}Zone '{zone_name}' loaded successfully."

  # --- Command Execution Messages ---
  error-no-permission: "{plugin-prefix}&cYou do not have permission to use this command."
  error-player-only-command: "{plugin-prefix}&cThis command can only be run by a player."
  error-unknown-subcommand: "{plugin-prefix}&cUnknown subcommand. Use &f/{command} &cfor help."
  error-usage-pos: "{plugin-prefix}&cUsage: &f/{command} {subcommand} <zone_name>"
  error-usage-define: "{plugin-prefix}&cUsage: &f/{command} define <zone_name>"
  error-usage-defaultaction: "{plugin-prefix}&cUsage: &f/{command} defaultaction <zone_name> <DENY|ALERT|ALLOW>"
  error-usage-setaction: "{plugin-prefix}&cUsage: &f/{command} setaction <zone_name> <material> <DENY|ALERT|ALLOW>"
  error-usage-remove: "{plugin-prefix}&cUsage: &f/{command} remove <zone_name>"
  error-usage-banned: "{plugin-prefix}/{command} banned <add|remove|list> &f- Manage globally banned materials."
  error-usage-banned-add: "{plugin-prefix}&cUsage: &f/{command} banned add <material>"
  error-usage-banned-remove: "{plugin-prefix}&cUsage: &f/{command} banned remove <material>"
  error-zone-not-found: "{plugin-prefix}&cZone '{zone_name}' not found."
  error-invalid-action: "{plugin-prefix}&cInvalid action '{action}'. Must be DENY, ALERT, or ALLOW."
  error-invalid-material: "{plugin-prefix}&cInvalid material '{material}'."
  error-invalid-material-or-action: "{plugin-prefix}&cInvalid material '{material}' or action '{action}'."
  error-define-no-selection: "{plugin-prefix}&cCannot define zone. Please set both pos1 ({pos1_status}) and pos2 ({pos2_status}) first."
  error-define-different-worlds: "{plugin-prefix}&cYour pos1 and pos2 selections are in different worlds!"
  action-denied-container-access: "{plugin-prefix}&cYou are not allowed to access &f{material} &cin zone &f{zone_name}&c (World: {world}, {x},{y},{z})."


  # --- Wand and Zone Management Success Messages ---
  wand-given: "{plugin-prefix}You have been given the AutoInform Wand! &eRight-Click for Pos1, Left-Click for Pos2."
  command-pos1-selected: "{plugin-prefix}&aPos1 set at &f{location}&a."
  command-pos2-selected: "{plugin-prefix}&aPos2 set at &f{location}&a."
  command-pos-set: "{plugin-prefix}&a{position} for zone &f{zone_name} &aset at &f{location}&a."
  command-define-new-zone: "{plugin-prefix}&aNew zone &f{zone_name} &ato be defined."
  command-define-updated-zone: "{plugin-prefix}&aZone &f{zone_name} &ahas been updated."
  command-define-success: "{plugin-prefix}&aZone &f{zone_name} &ahas been defined/updated successfully."
  default-action-set: "{plugin-prefix}&aDefault action for zone &f{zone_name} &aset to &f{action}&a."
  material-action-set: "{plugin-prefix}&aAction for &f{material} &ain zone &f{zone_name} &aset to &f{action}&a."
  command-remove-success: "{plugin-prefix}&aZone &f{zone_name} &ahas been removed."
  command-remove-not-found: "{plugin-prefix}&cZone &f{zone_name} &cnot found."
  command-defaultaction-usage: "{plugin-prefix}&cUsage: &f/{command} defaultaction <zone_name> <DENY|ALERT|ALLOW>"
  command-setaction-usage: "{plugin-prefix}&cUsage: &f/{command} setaction <zone_name> <material> <DENY|ALERT|ALLOW>"
  command-removeaction-usage: "{plugin-prefix}&cUsage: &f/{command} removeaction <zone_name> <material>"
  command-removeaction-success: "{plugin-prefix}&aAction for &f{material} &aremoved from zone &f{zone_name}&a."
  command-removeaction-not-found: "{plugin-prefix}&cNo specific action found for &f{material} &cin zone &f{zone_name}&c."
  command-defaultaction-zone-not-found: "{plugin-prefix}&cZone &f{zone_name} &cnot found to set default action."
  command-setaction-zone-not-found: "{plugin-prefix}&cZone &f{zone_name} &cnot found to set material action."
  command-removeaction-zone-not-found: "{plugin-prefix}&cZone &f{zone_name} &cnot found to remove material action."
  wand-selections-cleared: "{plugin-prefix}&aYour wand selections have been cleared."
  wand-selection-cleared-for-zone: "{plugin-prefix}&aWand selections for zone &f{zone_name} &acleared."
  banned-material-added: "{plugin-prefix}&aMaterial &f{material} &ahas been added to the globally banned list."
  banned-material-removed: "{plugin-prefix}&aMaterial &f{material} &ahas been removed from the globally banned list."
  banned-material-already-added: "{plugin-prefix}&cMaterial &f{material} &cis already on the globally banned list."
  banned-material-not-found: "{plugin-prefix}&cMaterial &f{material} &cwas not found on the globally banned list."
  plugin-no-banned-materials: "{plugin-prefix}&cNo globally banned materials defined."
  plugin-no-zones-defined: "{plugin-prefix}&cNo AutoInform zones defined."
  command-info-not-found: "{plugin-prefix}&cZone &f{zone_name} &cnot found."


  # --- Info & List Command Messages ---
  command-info-header: "{plugin-prefix}--- Zone Info: &f{zone_name} &e---"
  info-header-all: "{plugin-prefix}--- All AutoInform Zones ({count} total) ---"
  info-list-entry: "&7- &f{zone_name} &e(World: {world}, {corner1} to {corner2}) - Default: &f{default_action}"
  info-name: "&7Name: &f{zone_name}"
  info-world: "&7World: &f{world}"
  info-corner1: "&7Corner 1: &f{corner1}"
  info-corner2: "&7Corner 2: &f{corner2}"
  info-default-action: "&7Default Action: &f{action}"
  info-material-actions-header: "&7Material Specific Actions:"
  info-material-action-entry: "  &7- &f{material}&7: &f{action}"
  info-no-material-actions: "&7No material specific actions defined for this zone."
  list-header: "{plugin-prefix}--- Defined AutoInform Zones ({count} total) ---"
  list-entry: "&7- &f{zone_name}"


  # --- Action/Alert Messages (Sent to player or staff) ---
  action-denied: "{plugin-prefix}&cYou are not allowed to place/empty &f{material} &cin zone &f{zone_name}&c (World: {world}, {x},{y},{z})."
  action-alert: "{plugin-prefix}&eALERT: &f{player} &eplaced/emptied &f{material} &ein zone &f{zone_name}&e (World: {world}, {x},{y},{z})."
  alert-container-access: "{plugin-prefix}&eALERT: &f{player} &eaccessed &f{material} &ein zone &f{zone_name}&e (World: {world}, {x},{y},{z})."
  action-allowed: "{plugin-prefix}&aAllowed: &f{player} &aplaced/emptied &f{material} &ain zone &f{zone_name}&a (World: {world}, {x},{y},{z})."


  # Console logging messages (no prefix added as they are usually for internal server logs)
  action-denied-console: "DENIED: {player} tried to place/empty {material} in zone {zone_name} (World: {world}, {x},{y},{z})."
  action-alert-console: "ALERT: {player} placed/emptied {material} in zone {zone_name} (World: {world}, {x},{y},{z})."
  action-allowed-console: "ALLOWED: {player} placed/emptied {material} in zone {zone_name} (World: {world}, {x},{y},{z})."
  error-message-key-not-found: "[AlexxAutoWarn] [AutoInform] Error: Log message key '{key}' not found."

  # --- Debug Messages (ensure these are present and match what is in your AutoInformCommandExecutor) ---
  command-debug-on: "DEBUG: Debug logging enabled."
  command-debug-off: "DEBUG: Debug logging disabled."
  command-debug-on-console: "DEBUG: Debug logging ENABLED for {player}."
  command-debug-off-console: "DEBUG: Debug logging DISABLED for {player}."
  debug-pos-saved: "DEBUG: Player {player} saved {position} for zone '{zone_name}' at {location_string}. Current JSON: {current_json}"
  debug-define-start: "DEBUG: Define command initiated by {player} for zone '{zone_name}'. Raw selections JSON: {raw_json}"
  debug-define-selections: "DEBUG: Define for zone '{zone_name}'. Pos1 status: {pos1_status}, Pos2 status: {pos2_status}"
  debug-player-selection-get: "DEBUG: Getting player selection for {player_uuid}. JSON: {json_string}"
  debug-player-selection-set: "DEBUG: Player selection for {player_uuid} updated. JSON: {json_string}"
  debug-invalid-location-string-format: "DEBUG: Invalid location string format: {location_string}"
  debug-location-parse-error: "DEBUG: Error parsing location string '{location_string}': {error}"

# --- Help Messages for /autoinform command ---
# These are referenced by MessageUtil.sendHelpMessage
main-help-header: "{plugin-prefix}--- AutoInform Help ({command}) ---"
main-help-wand: "{plugin-prefix}/{command} wand &f- Get the AutoInform wand."
main-help-pos1: "{plugin-prefix}/{command} pos1 <zone_name> &f- Set position 1 for a zone at your current block."
main-help-pos2: "{plugin-prefix}/{command} pos2 <zone_name> &f- Set position 2 for a zone at your current block."
main-help-define: "{plugin-prefix}/{command} define <zone_name> &f- Define or update a zone with your current wand selections."
main-help-defaultaction: "{plugin-prefix}/{command} defaultaction <zone_name> <DENY|ALERT|ALLOW> &f- Set the default action for materials in a zone."
main-help-setaction: "{plugin-prefix}/{command} setaction <zone_name> <material> <DENY|ALERT|ALLOW> &f- Set a specific action for a material in a zone."
main-help-removeaction: "{plugin-prefix}/{command} removeaction <zone_name> <material> &f- Remove a specific material action from a zone."
main-help-remove: "{plugin-prefix}/{command} remove <zone_name> &f- Remove a defined zone."
main-help-info: "{plugin-prefix}/{command} info [zone_name] &f- Show info for a specific zone or all zones."
main-help-list: "{plugin-prefix}/{command} list &f- List all defined zones."
main-help-clearwand: "{plugin-prefix}/{command} clearwand &f- Clear your wand selections."
main-help-reload: "{plugin-prefix}/{command} reload &f- Reload all zones and banned materials from config."
main-help-banned: "{plugin-prefix}/{command} banned <add|remove|list> &f- Manage globally banned materials."