# -------------------------------------------------- #
#                  AutoWarn Settings                 #
# -------------------------------------------------- #
settings:
  # If true, the plugin will monitor and enforce rules on container access (chests, furnaces, etc.).
  monitor-chest-access: true
  # If true, all ALLOWED actions will be logged to console for debugging.
  debug-log-allowed-actions: false
  # A list of materials that are banned everywhere, regardless of zone rules.
  globally-banned-materials:
    - TNT
    - LAVA_BUCKET

# -------------------------------------------------- #
#                     Messages                       #
#   Uses the MiniMessage format for all messages.    #
#   https://docs.adventure.kyori.net/minimessage     #
# -------------------------------------------------- #
messages:
  plugin-prefix: "<gray>[<#FFA500>AutoWarn</#FFA500>]</gray> "

  # Error Messages
  error:
    player-only: "<red>This command can only be run by a player."
    no-permission: "<red>You do not have permission to use this command."
    invalid-zone-name: "<red>Invalid zone name. Must be 3-32 alphanumeric characters, underscores, or dashes."
    zone-not-found: "<red>Zone '<zone>' not found."
    define-no-selection: "<red>You must set both position 1 and 2 before defining a zone."
    usage:
      define: "<red>Usage: /autowarn define <zone_name>"
      remove: "<red>Usage: /autowarn remove <zone_name>"

  # Action Feedback
  action:
    denied: "<red>You cannot do that here! (Zone: <zone>)"
    alert: "<yellow>Alert! <player> used <material> in zone <zone> at <location>."

  # Wand Feedback
  wand:
    name: "<gold>AutoWarn Selection Wand"
    lore1: "<gray>Left-click to set position 1."
    lore2: "<gray>Right-click to set position 2."
    pos1-set: "<green>Position 1 set to <white><coords></white>."
    pos2-set: "<green>Position 2 set to <white><coords></white>."

  # Command Feedback
  command:
    wand-given: "<green>You have been given the selection wand."
    pos-set: "<green>Position <pos> set to <white><coords></white>."
    define-success: "<green>Successfully defined zone '<gold><zone></gold>'."
    remove-success: "<green>Successfully removed zone '<gold><zone></gold>'."
    reload-success: "<green>AutoWarn configuration and zones have been reloaded."
    list-empty: "<yellow>There are no zones defined yet."
    list-header: "<gold>AutoWarn Zones (<count>):"
    # Help messages
    help-header: "<gold>--- AutoWarn Help ---"
    help:
      wand: "<yellow>/aw wand</yellow> <gray>- Gives you the selection wand."
      pos: "<yellow>/aw pos1|pos2</yellow> <gray>- Sets a selection point."
      # Add all other help messages here

# -------------------------------------------------- #
#                   Zone Definitions                 #
#  This section is managed by the plugin. Do not     #
#          edit manually unless you know what        #
#                  you are doing!                    #
# -------------------------------------------------- #
zones:
  example_zone:
    world: "world"
    corner1:
      x: 0.0
      y: 64.0
      z: 0.0
    corner2:
      x: 100.0
      y: 80.0
      z: 100.0
    default-action: "ALERT"
    material-actions:
      DIAMOND_BLOCK: "DENY"
      LAVA: "DENY"