# AutoInform Configuration

# This section defines multiple protected zones.
# Each zone can be configured to either alert staff or deny placement
# of banned materials within its boundaries.
zones:
  # Example Zone 1: Alerts staff only (default behavior)
  zone_alpha: # Unique name for this zone
    world: "world"
    corner1:
      x: 0.0
      y: -64.0
      z: 0.0
    corner2:
      x: 100.0
      y: 100.0
      z: 100.0
    # Set to true to prevent placement of banned materials in this zone.
    # Set to false (or omit) to only alert staff.
    deny-placement: false

  # Example Zone 2: Denies placement
  zone_beta: # Another unique name for a different zone
    world: "world_nether"
    corner1:
      x: -50.0
      y: 30.0
      z: -50.0
    corner2:
      x: 50.0
      y: 80.0
      z: 50.0
    deny-placement: true # This zone will deny placement of banned materials

# This section defines a list of materials that are banned from being placed
# within any of the defined zones.
# You can add or remove materials using the /ainformset banned add/remove commands.
banned-materials:
  - LAVA_BUCKET
  - TNT
  - TNT_MINECART
