main: net.alexxiconify.alexxautowarn.alexxautowarn
name: alexxautowarn
version: 1.0.1
api-version: 1.21
description: A modernized zone protection plugin for Paper.
website: https://github.com/Alexxiconify/AlexxAutoWarn
softdepend: [CoreProtect]
commands:
  autowarn:
    description: Main command for the AutoWarn plugin.
    usage: /<command> [subcommand] [args]
    aliases: [ aw ]
    permission: autowarn.admin.use
permissions:
  autowarn.admin.*:
    description: Grants access to all admin commands.
    children:
      autowarn.admin.use: true
  autowarn.admin.use:
    description: Allows use of the AutoWarn admin commands.
  autowarn.bypass:
    description: Allows players to bypass zone warnings and notifications.
  autowarn.bypass.all:
    description: Allows bypassing all zone restrictions (notifications, messages, actions).