name: AlexxAutoWarn
version: '1.0.0'
main: net.Alexxiconify.alexxAutoWarn.AlexxAutoWarn
api-version: '1.21'
author: Alexxiconify
description: A modernized zone protection plugin.
softdepend: [ CoreProtect ]
permissions:
  autowarn.admin.*:
    description: Grants access to all admin commands.
    children:
      autowarn.admin.use: true
      autowarn.admin.wand: true
      autowarn.admin.define: true
      autowarn.admin.remove: true
      autowarn.admin.list: true
      autowarn.admin.info: true
      autowarn.admin.setaction: true
      autowarn.admin.priority: true
      autowarn.admin.reload: true
      autowarn.admin.banned: true
  autowarn.wand:
    description: Allows use of the selection wand.
    default: op
  autowarn.pos:
    description: Allows setting selection positions.
    default: op
  autowarn.define:
    description: Allows defining zones.
    default: op
  autowarn.remove:
    description: Allows removing zones.
    default: op
  autowarn.list:
    description: Allows listing zones.
    default: op
  autowarn.info:
    description: Allows viewing zone information.
    default: op
  autowarn.defaultaction:
    description: Allows setting default actions for zones.
    default: op
  autowarn.setaction:
    description: Allows setting material actions in zones.
    default: op
  autowarn.removeaction:
    description: Allows removing material actions from zones.
    default: op
  autowarn.priority:
    description: Allows setting zone priorities.
    default: op
  autowarn.banned:
    description: Allows managing globally banned materials.
    default: op
  autowarn.reload:
    description: Allows reloading the plugin configuration.
    default: op
  autowarn.bypass:
    description: Bypasses all zone restrictions.
    default: op
  autowarn.notify:
    description: Receives alerts for actions in zones.
    default: op