main: net.Alexxiconify.alexxAutoWarn.AlexxAutoWarn
version: 1.0.0
api-version: 1.20
name: AlexxAutoWarn
commands:
  autoinform:
    description: Manages AutoInform zones and settings.
    usage: /<command> <subcommand>
    aliases: [ ainform, alexxautowarn ]
    permission: alexxautowarn.admin.set
    permission-message: You do not have permission to use this command.
permissions:
  alexxautowarn.admin.set:
    description: Allows setting and managing AutoInform zones and plugin settings.
    default: op
  alexxautowarn.alert.receive:
    description: Allows a player to receive in-game alerts when a monitored action occurs.
    default: op
  alexxautowarn.bypass:
    description: Allows a player to bypass all AutoInform zone restrictions (no denials or alerts).
    default: op
  alexxautowarn.command.wand:
    description: Allows a player to get the AutoInform wand.
    default: op
  alexxautowarn.command.pos1:
    description: Allows a player to set position 1 for a zone.
    default: op
  alexxautowarn.command.pos2:
    description: Allows a player to set position 2 for a zone.
    default: op
  alexxautowarn.command.define:
    description: Allows a player to define or update a zone.
    default: op
  alexxautowarn.command.defaultaction:
    description: Allows a player to set the default action for a zone.
    default: op
  alexxautowarn.command.setaction:
    description: Allows a player to set specific material actions for a zone.
    default: op
  alexxautowarn.command.remove:
    description: Allows a player to remove zones or material actions.
    default: op
  alexxautowork.command.info:
    description: Allows a player to view zone information.
    default: op
  alexxautowarn.command.list:
    description: Allows a player to list all defined zones.
    default: op
  alexxautowarn.command.clearwand:
    description: Allows a player to clear their wand selections.
    default: op
  alexxautowarn.command.reload:
    description: Allows a player to reload the plugin configuration.
    default: op
  alexxautowarn.command.banned:
    description: Allows a player to manage globally banned materials.
    default: op
  alexxautowarn.command.togglechestmonitor:
    description: Allows a player to toggle chest access monitoring.
    default: op
  alexxautowarn.command.debug:
    description: Allows a player to toggle debug logging.
    default: op