#file: noinspection SpellCheckingInspection
name: AlexxAutoWarn
version: '1.0.0-SNAPSHOT'
main: net.Alexxiconify.alexxAutoWarn.AlexxsAutoWarn.AlexxAutoWarn
api-version: '1.21'
commands:
  ainformset: # Renamed from lzdset
    description: Manages AutoInform zones and banned materials.
    usage: /ainformset <subcommand>
    permission: autoinform.admin.set # Renamed permission
permissions:
  autoinform.admin.set: # Renamed permission
    description: Allows access to AutoInform zone and banned material setting commands.
    default: op