#file: noinspection SpellCheckingInspection
main: net.Alexxiconify.alexxAutoWarn.AlexxAutoWarn
version: 1.0.0
api-version: 1.20
name: AlexxAutoWarn
commands:
  autoinform:
    description: Manages AutoInform zones and settings.
    usage: /<command> <subcommand>
    aliases: [ ainform ]
    permission: autoinform.admin.set
    permission-message: You do not have permission to use this command.
permissions:
  autoinform.admin.set:
    description: Allows setting and managing AutoInform zones and plugin settings.
    default: true
  autoinform.alert.receive:
    description: Allows a player to receive in-game alerts when a monitored action occurs.
    default: true
  autoinform.bypass:
    description: Allows a player to bypass all AutoInform zone restrictions (no denials or alerts).
    default: true